export type AssetName =
   | "heroImage"
   | "userExclamationIcon"
   | "magnifyingGlassIcon"
   | "heartIcon"
   | "heartLightIcon"
   | "shoppingCartIcon"
   | "shareIcon"
   | "compareIcon"
   | "inspirationImage1"
   | "inspirationImage2"
   | "inspirationImage3"
   | "inspirationImage4"
   | "inspirationImage5"
   | "inspirationImage6"
   | "inspirationImage7"
   | "inspirationImage8"
   | "inspirationImage9";
